### ISSUE TITLE
关于项目部署疑问

### ISSUE THREAD

**Issue by ZangoZ** [hujianhong/Duang#1]
我在Eclipse中引入该Maven项目，Update时报错，报错 Cannot nest 'luobo/src/main/java/resources' inside'luobo/src/main/java/'。望您解惑，谢谢。

**Comment by hujianhong** [comment]
我暂时也不清楚怎么回事，你可以先告诉我你的开发环境配置比如eclipse版本，maven版本，以及如何导入maven项目的！
